# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build-push-ecr:
    docker:
    - image: docker:dind
    environment:
      BUILD_ID: << pipeline.number >>
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: Build ruby
          command: |
           cd ruby-img
           docker build -f Dockerfile -t "PLACEHOLDER.ecr.us-east-2.amazonaws.com/ruby-img:${BUILD_ID}" .
      - run:
          name: Build react
          command: |
           cd react-img
           docker build -f Dockerfile -t "PLACEHOLDER.ecr.us-east-2.amazonaws.com/react-img:${BUILD_ID}" .
      - run:
          name: Push new images to ECR
          command: |
           apk update
           apk add py3-pip
           pip3 install awscli
           aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin PLACEHOLDER.ecr.us-east-2.amazonaws.com
           docker push "PLACEHOLDER.ecr.us-east-2.amazonaws.com/ruby-img:${BUILD_ID}" .
           docker push "PLACEHOLDER.ecr.us-east-2.amazonaws.com/react-img:${BUILD_ID}" . 
 
# Invoke jobs via workflows
workflows:
  ecr-workflow:
    jobs:
      - build-push-ecr
      - deploy:
          requires:
            - build-push-ecr
